project_id = "ctyblvmermwkcuavzkdr"

[functions.delete-account]
verify_jwt = false

[functions.evaluate-writing]
verify_jwt = false

[functions.set-api-key]
verify_jwt = false

[functions.test-api-key]
verify_jwt = false
