-- N-Deklination: mixed exercises with negative examples (regular nouns)
-- The user must decide WHETHER to apply N-Deklination, not just HOW

INSERT INTO exercises (topic, area, level, exercise_type, sort_order, title_de, title_en, instructions_de, instructions_en, content, solution, explanation_de, explanation_en) VALUES

('n_deklination', 'grammar', 'c1', 'fill_in', 20,
 'N-Deklination oder nicht? 1', 'N-declension or not? 1',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Der Präsident___ hat die Rede gehalten.", "hint": "Nominativ — braucht das Nomen eine Endung?"}',
 '{"correct": "—", "accept_also": ["-"]}',
 'Im Nominativ bleibt das Nomen in der Grundform: der Präsident. Die N-Deklination greift nur im Akkusativ, Dativ und Genitiv.',
 'In nominative case, the noun stays unchanged: der Präsident. N-declension only applies in accusative, dative, and genitive.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 21,
 'N-Deklination oder nicht? 2', 'N-declension or not? 2',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Ich habe den Architekt___ um Rat gefragt.", "hint": "Akkusativ — N-Deklination oder nicht?"}',
 '{"correct": "en"}',
 'Der Architekt ist ein N-Deklination-Nomen (männlich, endet auf -t, bezeichnet eine Person). Im Akkusativ: den Architekten.',
 'Architekt is an N-declension noun (masculine, ends in -t, denotes a person). Accusative: den Architekten.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 22,
 'N-Deklination oder nicht? 3', 'N-declension or not? 3',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Ich habe den Lehrer___ nach der Stunde gefragt.", "hint": "Akkusativ — N-Deklination oder nicht?"}',
 '{"correct": "—", "accept_also": ["-"]}',
 'Der Lehrer folgt NICHT der N-Deklination, obwohl er männlich ist und eine Person bezeichnet. Nur Nomen mit bestimmten Endungen (-e, -ent, -ant, -ist, -at, -oge, -graf) gehören dazu.',
 'Lehrer does NOT follow N-declension, even though it is masculine and denotes a person. Only nouns with specific endings (-e, -ent, -ant, -ist, -at, -oge, -graf) belong to this group.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 23,
 'N-Deklination oder nicht? 4', 'N-declension or not? 4',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Die Forschung des Biologe___ wurde veröffentlicht.", "hint": "Genitiv — N-Deklination oder nicht?"}',
 '{"correct": "n"}',
 'Der Biologe endet auf -e und bezeichnet eine Person → N-Deklination. Im Genitiv: des Biologen.',
 'Biologe ends in -e and denotes a person → N-declension. Genitive: des Biologen.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 24,
 'N-Deklination oder nicht? 5', 'N-declension or not? 5',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Die Meinung des Sprecher___ war eindeutig.", "hint": "Genitiv — N-Deklination oder nicht?"}',
 '{"correct": "s"}',
 'Der Sprecher folgt NICHT der N-Deklination. Im Genitiv bekommt er die normale Endung -s: des Sprechers.',
 'Sprecher does NOT follow N-declension. In genitive, it takes the regular -s ending: des Sprechers.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 25,
 'N-Deklination oder nicht? 6', 'N-declension or not? 6',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Wir haben mit dem Diplomat___ verhandelt.", "hint": "Dativ — N-Deklination oder nicht?"}',
 '{"correct": "en"}',
 'Der Diplomat endet auf -at und bezeichnet eine Person → N-Deklination. Im Dativ: dem Diplomaten.',
 'Diplomat ends in -at and denotes a person → N-declension. Dative: dem Diplomaten.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 26,
 'N-Deklination oder nicht? 7', 'N-declension or not? 7',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Wir haben mit dem Ingenieur___ gesprochen.", "hint": "Dativ — N-Deklination oder nicht?"}',
 '{"correct": "—", "accept_also": ["-"]}',
 'Der Ingenieur folgt NICHT der N-Deklination. Im Dativ bleibt er unverändert: dem Ingenieur. Obwohl das Wort auf -eur endet, gehört es nicht zu den N-Deklination-Endungen.',
 'Ingenieur does NOT follow N-declension. In dative it stays unchanged: dem Ingenieur. Although it ends in -eur, this is not one of the N-declension endings.'),

('n_deklination', 'grammar', 'c1', 'fill_in', 27,
 'N-Deklination: Sonderfall', 'N-declension: special case',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Die Bedeutung des Name___ ist unklar.", "hint": "Genitiv — Achtung: Sonderfall!"}',
 '{"correct": "ns"}',
 'Der Name ist ein Sonderfall der N-Deklination: Akkusativ/Dativ → den/dem Namen, aber Genitiv → des Namens (mit -ns!).',
 'Name is a special case of N-declension: accusative/dative → den/dem Namen, but genitive → des Namens (with -ns!).'),

('n_deklination', 'grammar', 'c1', 'fill_in', 28,
 'N-Deklination oder nicht? 8', 'N-declension or not? 8',
 'Ergänze die richtige Endung. Wenn keine Endung nötig ist, schreibe —.',
 'Add the correct ending. If no ending is needed, write —.',
 '{"sentence": "Er hat den Computer___ repariert.", "hint": "Akkusativ — N-Deklination oder nicht?"}',
 '{"correct": "—", "accept_also": ["-"]}',
 'Der Computer folgt NICHT der N-Deklination. Die N-Deklination gilt nur für bestimmte maskuline Nomen, die Personen oder Lebewesen bezeichnen.',
 'Computer does NOT follow N-declension. N-declension only applies to certain masculine nouns denoting people or living beings.'),

('n_deklination', 'grammar', 'c1', 'multiple_choice', 29,
 'Korrekte Form erkennen 1', 'Identify correct form 1',
 'Welcher Satz ist grammatisch korrekt?',
 'Which sentence is grammatically correct?',
 '{"options": ["Ich habe den Studenten gefragt.", "Ich habe den Studentens gefragt.", "Ich habe den Student gefragt.", "Ich habe den Studentem gefragt."], "question": "Welcher Satz ist grammatisch korrekt?"}',
 '{"correct": 0}',
 'Student ist ein N-Deklination-Nomen (endet auf -ent, bezeichnet eine Person). Im Akkusativ: den Studenten.',
 'Student is an N-declension noun (ends in -ent, denotes a person). Accusative: den Studenten.'),

('n_deklination', 'grammar', 'c1', 'multiple_choice', 30,
 'Korrekte Form erkennen 2', 'Identify correct form 2',
 'Welcher Satz ist grammatisch korrekt?',
 'Which sentence is grammatically correct?',
 '{"options": ["Er sprach mit dem Nachbar.", "Er sprach mit dem Nachbarn.", "Er sprach mit dem Nachbaren.", "Er sprach mit dem Nachbars."], "question": "Welcher Satz ist grammatisch korrekt?"}',
 '{"correct": 1}',
 'Der Nachbar ist ein N-Deklination-Nomen. Im Dativ: dem Nachbarn. Achtung: nicht -en, sondern nur -n, weil das Wort bereits auf -r endet.',
 'Nachbar is an N-declension noun. Dative: dem Nachbarn. Note: only -n, not -en, because the word already ends in -r.'),

('n_deklination', 'grammar', 'c1', 'multiple_choice', 31,
 'Korrekte Form erkennen 3', 'Identify correct form 3',
 'Welcher Satz ist grammatisch korrekt?',
 'Which sentence is grammatically correct?',
 '{"options": ["Die Idee des Professoren war brillant.", "Die Idee des Professors war brillant.", "Die Idee des Professorens war brillant.", "Die Idee des Professor war brillant."], "question": "Welcher Satz ist grammatisch korrekt?"}',
 '{"correct": 1}',
 'Achtung: Professor folgt NICHT der N-Deklination! Genitiv: des Professors (normale -s Endung). Viele denken, weil Professor eine Person bezeichnet, gehört es dazu — aber die Endung -or ist keine N-Deklination-Endung.',
 'Careful: Professor does NOT follow N-declension! Genitive: des Professors (regular -s ending). Many assume it belongs because it denotes a person — but -or is not an N-declension ending.'),

('n_deklination', 'grammar', 'c1', 'multiple_choice', 32,
 'N-Deklination ausschließen', 'Exclude N-declension',
 'Welches Nomen folgt NICHT der N-Deklination?',
 'Which noun does NOT follow N-declension?',
 '{"options": ["der Kunde", "der Kollege", "der Bruder", "der Junge"], "question": "Welches Nomen folgt NICHT der N-Deklination?"}',
 '{"correct": 2}',
 'Der Bruder folgt nicht der N-Deklination. Obwohl er männlich ist und eine Person bezeichnet, hat er keine der typischen Endungen (-e, -ent, -ant, -ist, -at, -oge). Genitiv: des Bruders, nicht des Brudern.',
 'Bruder does not follow N-declension. Although masculine and denoting a person, it lacks the typical endings (-e, -ent, -ant, -ist, -at, -oge). Genitive: des Bruders, not des Brudern.');
